### ISSUE TITLE
Mac OS X: bash_profile doesn't contain date of installation of gid

### ISSUE THREAD

**Issue by xennygrimmato** [ashmew2/gid-get-it-done#3]
Expected comment in `.bash_profile`: `Automatically added by gid installer at [DATE]`

Currently, the date seems to get omitted during installation. On a Mac, if when I run: `echo "## Automatically added by gid installer at $(date --utc)"` on bash, I get:

```
date: illegal option -- -
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
## Automatically added by gid installer at
```

It seems that `date` doesn't recognize the `--utc` flag.

**Comment by ashmew2** [comment]
Fixed by xennygrimmato in ba5c8012094c9859616ec3b1835a76d95d66f0dd.
Thanks!
